//
// Created by 03vic on 11/30/2022.
//

#ifndef INTERPOLATION_AND_REGRESSION_INTERPOLATION_H
#define INTERPOLATION_AND_REGRESSION_INTERPOLATION_H

#endif //INTERPOLATION_AND_REGRESSION_INTERPOLATION_H
